// ============================================
// Visual Mnemonics for Japanese Characters
// Each entry: { visual: "emoji/ascii art", story: "short mnemonic" }
// ============================================

const MNEMONICS = {

// ==========================================
// HIRAGANA MNEMONICS
// ==========================================
"あ": { visual: "🍎", story: "An Antenna on an apple — 'Ah, an apple!'" },
"い": { visual: "🐟🐟", story: "Two eels swimming — 'ee-ls!'" },
"う": { visual: "🦄", story: "A Unicorn's head in profile — 'oo-nicorn'" },
"え": { visual: "🏗️", story: "An Elevator going up — 'Eh? Going up?'" },
"お": { visual: "⛳", story: "A golf player swinging — 'Oh nice shot!'" },
"か": { visual: "🔪", story: "A sharp Knife Cutting — 'Ka-t!'" },
"き": { visual: "🔑", story: "A Key with two bumps — 'ki-y'" },
"く": { visual: "🦅", story: "A bird's beak — 'Koo-koo!'" },
"け": { visual: "🚪", story: "A door with a Keg next to it" },
"こ": { visual: "🐛", story: "Two worms, a CO-uple of them" },
"さ": { visual: "🏄", story: "A Surfer riding a wave — 'SA-rf's up!'" },
"し": { visual: "🎣", story: "A fish hook — 'SHI caught a fish!'" },
"す": { visual: "🍜", story: "Noodles on a chopstick — 'SU-rp!'" },
"せ": { visual: "🗣️", story: "A mouth SAY-ing something — 'SE-y!'" },
"そ": { visual: "🧵", story: "Thread going through a needle — 'SO sewing'" },
"た": { visual: "✝️", story: "Looks like 'ta' — a cross with a dash" },
"ち": { visual: "🍵", story: "A cup of CHI tea with steam" },
"つ": { visual: "🌊", story: "A TSU-nami wave curling!" },
"て": { visual: "🤚", story: "A hand reaching out — 'TE' means hand!" },
"と": { visual: "🦶", story: "A TOe stub — the top is the nail!" },
"な": { visual: "🪢", story: "A kNOt being tied — 'NA-t'" },
"に": { visual: "🝆", story: "Looks like 'ニ' (knee) — two horizontal lines" },
"ぬ": { visual: "🍜", story: "NOOdles all tangled up — 'NU-dles'" },
"ね": { visual: "🐱", story: "A cat (NEko) curled up — 'NE'" },
"の": { visual: "🚫", story: "'NO' — a circle like the No sign" },
"は": { visual: "🏠", story: "A HAuse (house) with an antenna — 'HA'" },
"ひ": { visual: "😊", story: "A smiling face — 'HEE hee!' laughing" },
"ふ": { visual: "🗻", story: "Mt. FUji with a wind blowing — 'FU!'" },
"へ": { visual: "⛰️", story: "A mountain peak — 'HE-y, nice view!'" },
"ほ": { visual: "🐴", story: "A HOrs-e galloping — see the legs?" },
"ま": { visual: "Ⓜ️", story: "MAma has big eyes — looks like face with headband" },
"み": { visual: "🔢", story: "Looks like the number 21 — 'MI (3) needs two strokes'" },
"む": { visual: "🐄", story: "A cow says 'MOO' — 'MU'" },
"め": { visual: "👁️", story: "An eye with eyelashes — 'ME' means eye!" },
"も": { visual: "🪱", story: "A worm with legs — 'MO-re legs than expected'" },
"や": { visual: "⚓", story: "A YAcht anchor — 'YA'" },
"ゆ": { visual: "🐡", story: "A fish on a hook — 'YU caught one!'" },
"よ": { visual: "🧘", story: "A person doing YOga on a mat" },
"ら": { visual: "🦝", story: "A RAccoon face — 'RA'" },
"り": { visual: "🌾", story: "Two REEds growing — 'RI'" },
"る": { visual: "🛤️", story: "Like a ROOd/path with a loop — 'RU'" },
"れ": { visual: "🏃", story: "Someone in a RAce — 'RE'" },
"ろ": { visual: "3️⃣", story: "Looks like the number 3 — 'RO-tate it!'" },
"わ": { visual: "🦢", story: "A swan on WAter — 'WA'" },
"を": { visual: "🏋️", story: "A weightlifter — 'WO!' Heavy!" },
"ん": { visual: "🤔", story: "Someone thinking 'hmm-N' — chin on hand" },

// Dakuten G
"が": { visual: "🔪\"", story: "か + force dots = GA — harder K sound" },
"ぎ": { visual: "🔑\"", story: "き + force dots = GI — voiced key" },
"ぐ": { visual: "🦅\"", story: "く + force dots = GU — louder bird" },
"げ": { visual: "🚪\"", story: "け + force dots = GE — door slammed!" },
"ご": { visual: "🐛\"", story: "こ + force dots = GO — worms GO away" },
// Dakuten Z
"ざ": { visual: "🏄\"", story: "さ + dots = ZA — surfer in a storm" },
"じ": { visual: "🎣\"", story: "し + dots = JI — bigger fish!" },
"ず": { visual: "🍜\"", story: "す + dots = ZU — slurping louder" },
"ぜ": { visual: "🗣️\"", story: "せ + dots = ZE — shouting now" },
"ぞ": { visual: "🧵\"", story: "そ + dots = ZO — sewing faster" },
// Dakuten D
"だ": { visual: "✝️\"", story: "た + dots = DA — DAddy cross" },
"ぢ": { visual: "🍵\"", story: "ち + dots = DI — strong tea" },
"づ": { visual: "🌊\"", story: "つ + dots = DU — bigger wave" },
"で": { visual: "🤚\"", story: "て + dots = DE — hand clapping" },
"ど": { visual: "🦶\"", story: "と + dots = DO — stomping foot" },
// Dakuten B
"ば": { visual: "🏠\"", story: "は + dots = BA — BAng on house" },
"び": { visual: "😊\"", story: "ひ + dots = BI — big BEam smile" },
"ぶ": { visual: "🗻\"", story: "ふ + dots = BU — wind BUffets Mt Fuji" },
"べ": { visual: "⛰️\"", story: "へ + dots = BE — BEautiful peak" },
"ぼ": { visual: "🐴\"", story: "ほ + dots = BO — horse BOlts" },
// Handakuten P
"ぱ": { visual: "🏠°", story: "は + circle = PA — PArty at house" },
"ぴ": { visual: "😊°", story: "ひ + circle = PI — PIck a smile" },
"ぷ": { visual: "🗻°", story: "ふ + circle = PU — PUff of wind" },
"ぺ": { visual: "⛰️°", story: "へ + circle = PE — PEak with snow" },
"ぽ": { visual: "🐴°", story: "ほ + circle = PO — POny trots" },

// ==========================================
// KATAKANA MNEMONICS
// ==========================================
"ア": { visual: "⛏️", story: "An Axe chopping — 'A' for axe" },
"イ": { visual: "🏃", story: "A person leaning forward — walking East" },
"ウ": { visual: "📦", story: "A box with a lid — 'OO'-pen the box" },
"エ": { visual: "🏗️", story: "An I-beam/girder — Engineering 'E'" },
"オ": { visual: "⚾", story: "A baseball player swinging — 'O' for out!" },
"カ": { visual: "⚔️", story: "A sword in a stand — 'KA-tana'" },
"キ": { visual: "🗝️", story: "A skeleton KEY — 'KI'" },
"ク": { visual: "📐", story: "A right angle/corner — 'KU-rner'" },
"ケ": { visual: "🦵", story: "A bent leg — 'KE' like a kick" },
"コ": { visual: "📦", story: "An open box/COrner — 'KO'" },
"サ": { visual: "🍺", story: "A SAke bottle — 'SA'" },
"シ": { visual: "😉", story: "A winking face — 'SHI' is happy!" },
"ス": { visual: "⛷️", story: "A Ski slope — 'SU-ki!'" },
"セ": { visual: "💺", story: "A SEat/chair — 'SE-t down'" },
"ソ": { visual: "🧊", story: "Two drops — 'SO' cold, dripping!" },
"タ": { visual: "⭐", story: "Looks like a TAll cross — 'TA'" },
"チ": { visual: "5️⃣", story: "Looks like number 5 — 'CHI-nco!'" },
"ツ": { visual: "😊", story: "A smiley face! 'TSU' happy — ツ' is the original emoji" },
"テ": { visual: "📻", story: "A TV antenna — 'TE-levision'" },
"ト": { visual: "🚪", story: "A TOrii gate half — 'TO'" },
"ナ": { visual: "✝️", story: "A cross/plus sign — 'NA' (like a knot)" },
"ニ": { visual: "=", story: "Two horizontal lines — equals 'NI' (two)!" },
"ヌ": { visual: "🔧", story: "A wrench — NOOdle wrench twisting" },
"ネ": { visual: "🪢", story: "A NEt catching fish" },
"ノ": { visual: "✏️", story: "Just one stroke, like a NOte slash" },
"ハ": { visual: "⛺", story: "A tent opening — 'HA HA' laughing in tent" },
"ヒ": { visual: "🔑", story: "HE has a key — flipped" },
"フ": { visual: "🎵", story: "A musical note — 'FU-n music'" },
"ヘ": { visual: "⛰️", story: "Same as hiragana — mountain peak 'HE'" },
"ホ": { visual: "⛪", story: "A HOly cross with extra strokes" },
"マ": { visual: "♏", story: "Looks like MArk — horizontal with angle" },
"ミ": { visual: "3️⃣", story: "Three horizontal lines — 'MI' = three!" },
"ム": { visual: "🐮", story: "A cow face — MOO = 'MU'" },
"メ": { visual: "✖️", story: "An X marks the spot — 'ME' X" },
"モ": { visual: "📝", story: "MOre lines stacked up" },
"ヤ": { visual: "⚓", story: "A YAcht anchor — same as hiragana" },
"ユ": { visual: "🏺", story: "A vase — 'YU-nique vessel'" },
"ヨ": { visual: "📖", story: "A book with bookmarks — 'YO-mu (to read)'" },
"ラ": { visual: "🎩", story: "A magician pulling RAbbit — 'RA'" },
"リ": { visual: "🫘", story: "Two beans — 'RI-ce beans'" },
"ル": { visual: "🦵", story: "A bent leg kicking — 'RU-n!'" },
"レ": { visual: "↗️", story: "An upward slash — 'RE-ach up!'" },
"ロ": { visual: "🔲", story: "A simple square — 'RO-om/box'" },
"ワ": { visual: "🌀", story: "A WAve spinning — 'WA'" },
"ヲ": { visual: "🏋️", story: "Heavy — 'WO!' Just like hiragana" },
"ン": { visual: "💫", story: "Something flying — 'N-ergy!'" },

// Katakana dakuten
"ガ": { visual: "⚔️\"", story: "カ + dots = GA — sword battle!" },
"ギ": { visual: "🗝️\"", story: "キ + dots = GI — golden key" },
"グ": { visual: "📐\"", story: "ク + dots = GU — sharper corner" },
"ゲ": { visual: "🦵\"", story: "ケ + dots = GE — harder kick" },
"ゴ": { visual: "📦\"", story: "コ + dots = GO — box delivered" },
"ザ": { visual: "🍺\"", story: "サ + dots = ZA — SAke spilling" },
"ジ": { visual: "😉\"", story: "シ + dots = JI — wink harder!" },
"ズ": { visual: "⛷️\"", story: "ス + dots = ZU — faster skiing" },
"ゼ": { visual: "💺\"", story: "セ + dots = ZE — seat shaking" },
"ゾ": { visual: "🧊\"", story: "ソ + dots = ZO — freezing cold" },
"ダ": { visual: "⭐\"", story: "タ + dots = DA — DArk star" },
"ヂ": { visual: "5️⃣\"", story: "チ + dots = DI — rare character" },
"ヅ": { visual: "😊\"", story: "ツ + dots = DU — rare character" },
"デ": { visual: "📻\"", story: "テ + dots = DE — DEcibel loud TV" },
"ド": { visual: "🚪\"", story: "ト + dots = DO — DOOR slam!" },
"バ": { visual: "⛺\"", story: "ハ + dots = BA — BAng in tent" },
"ビ": { visual: "🔑\"", story: "ヒ + dots = BI — BIg key" },
"ブ": { visual: "🎵\"", story: "フ + dots = BU — BUzzing music" },
"ベ": { visual: "⛰️\"", story: "ヘ + dots = BE — BEst view" },
"ボ": { visual: "⛪\"", story: "ホ + dots = BO — BOld church" },
"パ": { visual: "⛺°", story: "ハ + circle = PA — PArty tent" },
"ピ": { visual: "🔑°", story: "ヒ + circle = PI — PIck the lock" },
"プ": { visual: "🎵°", story: "フ + circle = PU — PUre melody" },
"ペ": { visual: "⛰️°", story: "ヘ + circle = PE — PEaceful peak" },
"ポ": { visual: "⛪°", story: "ホ + circle = PO — POlite church" },

// ==========================================
// KANJI MNEMONICS (visual decomposition)
// ==========================================
"一": { visual: "━", story: "ONE horizontal line = one. Simple!" },
"二": { visual: "═", story: "TWO horizontal lines. Count them!" },
"三": { visual: "≡", story: "THREE horizontal lines stacked!" },
"四": { visual: "🪟", story: "A window with FOUR panes inside a frame" },
"五": { visual: "🤸", story: "A person doing a FIVE-point star pose" },
"六": { visual: "🎆", story: "A top hat with legs — SIX strokes spreading" },
"七": { visual: "7️⃣", story: "Looks like an upside-down 7 — SEVEN!" },
"八": { visual: "🗻", story: "Two slopes spreading apart — EIGHT is wide" },
"九": { visual: "🦎", story: "A lizard curling — NINE lives like a cat" },
"十": { visual: "✚", story: "A plus/cross — TEN fingers crossed" },
"百": { visual: "💯", story: "One + white = HUNDRED. 一 on top of 白" },
"千": { visual: "🌾", story: "A thousand stalks of grain swaying" },
"万": { visual: "🙌", story: "Hands spread wide — TEN THOUSAND things" },
"円": { visual: "💴", story: "A yen coin — YEN/circle, round money" },
"日": { visual: "☀️", story: "The SUN in a box — DAY/sun" },
"月": { visual: "🌙", story: "The MOON — crescent with lines inside" },
"火": { visual: "🔥", story: "A person with arms up = FIRE spreading!" },
"水": { visual: "💧", story: "A river with splashing WATER drops" },
"木": { visual: "🌳", story: "A TREE — trunk in center, branches out" },
"金": { visual: "🥇", story: "A king wearing a crown = GOLD/metal" },
"土": { visual: "🏔️", story: "A cross on the ground = EARTH/soil" },
"年": { visual: "📅", story: "A person carrying grain = YEAR of harvest" },
"時": { visual: "⏰", story: "Sun 日 + temple 寺 = TIME at the temple" },
"分": { visual: "🔪", story: "A knife 刀 splitting 八 = to DIVIDE/minute" },
"半": { visual: "½", story: "A standing figure cut in HALF" },
"毎": { visual: "🔄", story: "A mother 母 doing EVERY day routine" },
"今": { visual: "🏠", story: "A roof over a person = NOW, present moment" },
"先": { visual: "👣", story: "Feet walking AHEAD — previous/first" },
"来": { visual: "🚶", story: "A person COMING through grain — COME/next" },
"前": { visual: "🔜", story: "Moon + knife = cutting BEFORE time" },
"後": { visual: "🔙", story: "Walking + thread = trailing BEHIND/after" },
"午": { visual: "🕛", story: "A clock at 12 = NOON exactly" },
"間": { visual: "🚪☀️", story: "Sun seen through a gate = BETWEEN/interval" },
"週": { visual: "📆", story: "Road around — going full circle = WEEK" },
"人": { visual: "🚶", story: "Two legs walking = PERSON. Simplest kanji!" },
"男": { visual: "💪", story: "Field 田 + strength 力 = MAN working the field" },
"女": { visual: "💃", story: "A dancing figure = WOMAN. Graceful curves!" },
"子": { visual: "👶", story: "A baby with outstretched arms = CHILD" },
"母": { visual: "🤱", story: "Two dots are breasts = MOTHER nursing" },
"父": { visual: "👨", story: "Crossed axes = FATHER (strong protector)" },
"友": { visual: "🤝", story: "Two hands reaching = FRIEND" },
"目": { visual: "👁️", story: "An EYE turned sideways — see the pupil?" },
"耳": { visual: "👂", story: "An EAR — the shape literally shows one!" },
"口": { visual: "👄", story: "An open MOUTH — simple square opening" },
"手": { visual: "🤚", story: "A HAND with fingers spread on a stick" },
"足": { visual: "🦶", story: "A person's kneeling LEG/FOOT with toes" },
"国": { visual: "🗾", story: "A jewel 玉 inside borders □ = COUNTRY" },
"外": { visual: "🚪→", story: "Evening 夕 + divination 卜 = OUTSIDE at dusk" },
"中": { visual: "🎯", story: "An arrow through the CENTER = INSIDE/middle" },
"上": { visual: "⬆️", story: "A line ABOVE the base = UP/above" },
"下": { visual: "⬇️", story: "A line BELOW the top = DOWN/below" },
"右": { visual: "👉", story: "A hand 口 reaching RIGHT (eat with right)" },
"左": { visual: "👈", story: "A hand doing work ナ = LEFT hand" },
"北": { visual: "🧭", story: "Two people back-to-back fleeing cold = NORTH" },
"南": { visual: "🌴", story: "A plant growing inside shelter = warm SOUTH" },
"東": { visual: "🌅", story: "Sun 日 rising behind tree 木 = EAST" },
"西": { visual: "🌇", story: "Bird nesting at sunset = WEST" },
"山": { visual: "🏔️", story: "Three peaks = MOUNTAIN. Looks exactly like it!" },
"川": { visual: "🏞️", story: "Three flowing streams = RIVER. So visual!" },
"天": { visual: "😇", story: "One + big 大 = above a person = HEAVEN/sky" },
"気": { visual: "💨", story: "Steam rising from rice = SPIRIT/energy/air" },
"雨": { visual: "🌧️", story: "Drops falling from a cloud = RAIN" },
"電": { visual: "⚡", story: "Rain 雨 + lightning = ELECTRICITY" },
"車": { visual: "🚗", story: "A wheel with axle seen from top = CAR" },
"駅": { visual: "🚉", story: "Horse 馬 + measurement = STATION (horse stop)" },
"道": { visual: "🛤️", story: "A head walking forward = ROAD/way/path" },
"食": { visual: "🍽️", story: "A person at table with lid = EAT" },
"飲": { visual: "🥤", story: "Food radical + yawn/open = DRINK" },
"見": { visual: "👀", story: "An eye 目 on legs = SEE/look (walking around looking)" },
"聞": { visual: "👂🚪", story: "Ear 耳 at the gate 門 = HEAR/listen/ask" },
"読": { visual: "📖", story: "Words 言 + sell 売 = READ (buy words)" },
"書": { visual: "✍️", story: "A brush writing on paper = WRITE" },
"話": { visual: "💬", story: "Words 言 + tongue 舌 = TALK/speak" },
"言": { visual: "🗣️", story: "Sound waves from mouth = SAY/words" },
"行": { visual: "🚶‍♂️", story: "A crossroad — to GO somewhere" },
"出": { visual: "🚪→", story: "Two mountains popping OUT = EXIT/go out" },
"入": { visual: "🚪←", story: "A person stepping IN = ENTER" },
"立": { visual: "🧍", story: "A person STANDING on the ground" },
"休": { visual: "🌴🧍", story: "Person 亻next to tree 木 = REST in shade" },
"買": { visual: "🛒", story: "Net 罒 + shell/money 貝 = BUY" },
"会": { visual: "🤝", story: "A roof over people = MEET together" },
"生": { visual: "🌱", story: "A plant sprouting = LIFE/live/birth" },
"大": { visual: "🤸", story: "A person with arms wide = BIG!" },
"小": { visual: "🐜", story: "A tiny dividing line = SMALL" },
"多": { visual: "🌙🌙", story: "Two evenings stacked = MANY (so many nights)" },
"少": { visual: "🤏", story: "A small piece shaved off = FEW/little" },
"新": { visual: "🆕", story: "Standing 立 + tree 木 + axe 斤 = cut NEW wood" },
"古": { visual: "🏚️", story: "Ten 十 + mouth 口 = passed through ten mouths = OLD" },
"高": { visual: "🏢", story: "A tall building with gate = HIGH/expensive" },
"安": { visual: "🏠👩", story: "Woman 女 under roof 宀 = peaceful = CHEAP/safe" },
"長": { visual: "📏", story: "Long flowing hair = LONG" },
"白": { visual: "⬜", story: "A ray of sunlight = WHITE" },
"学": { visual: "🎓", story: "A child 子 under a roof studying = LEARN" },
"校": { visual: "🏫", story: "Tree 木 + crossed 交 = SCHOOL building" },
"語": { visual: "🗣️📖", story: "Words 言 + five 五 + mouth 口 = LANGUAGE" },
"何": { visual: "❓", story: "A person 亻carrying something — WHAT is it?" },
"名": { visual: "🏷️", story: "Evening 夕 + mouth 口 = calling out NAME in dark" },
"花": { visual: "🌸", story: "A plant that transforms = FLOWER blooming" },
"本": { visual: "📚", story: "A tree 木 with roots marked = BOOK/origin" },
"店": { visual: "🏪", story: "A roof with fortune 占 = SHOP (fortune at store)" },
"社": { visual: "⛩️", story: "Earth 土 + ceremony = COMPANY/shrine" },
};
