// ============================================
// Japanese Career Coach - Phrase Database
// NSK QC Digitalization context
// ============================================

const PHRASES = {
    greetings: [
        { jp: "おはようございます", romaji: "Ohayou gozaimasu", en: "Good morning (polite)" },
        { jp: "こんにちは", romaji: "Konnichiwa", en: "Good afternoon / Hello" },
        { jp: "こんばんは", romaji: "Konbanwa", en: "Good evening" },
        { jp: "はじめまして", romaji: "Hajimemashite", en: "Nice to meet you (first time)" },
        { jp: "私はレイザです", romaji: "Watashi wa Reyza desu", en: "My name is Reyza" },
        { jp: "よろしくお願いします", romaji: "Yoroshiku onegaishimasu", en: "Please take care of me / Nice to meet you" },
        { jp: "ありがとうございます", romaji: "Arigatou gozaimasu", en: "Thank you very much" },
        { jp: "すみません", romaji: "Sumimasen", en: "Excuse me / Sorry" },
        { jp: "分かりました", romaji: "Wakarimashita", en: "I understand" },
        { jp: "もう一度お願いします", romaji: "Mou ichido onegaishimasu", en: "Once more, please" },
        { jp: "日本語は勉強中です", romaji: "Nihongo wa benkyou-chuu desu", en: "I'm still studying Japanese" },
        { jp: "頑張ります", romaji: "Ganbarimasu", en: "I will do my best" },
        { jp: "お疲れ様です", romaji: "Otsukaresama desu", en: "Thanks for your hard work (daily greeting)" },
        { jp: "失礼します", romaji: "Shitsurei shimasu", en: "Excuse me (entering/leaving)" },
    ],
    workplace: [
        { jp: "会議", romaji: "Kaigi", en: "Meeting" },
        { jp: "報告", romaji: "Houkoku", en: "Report" },
        { jp: "確認", romaji: "Kakunin", en: "Confirmation / Check" },
        { jp: "承認", romaji: "Shounin", en: "Approval" },
        { jp: "提出", romaji: "Teishutsu", en: "Submission" },
        { jp: "締め切り", romaji: "Shimekiri", en: "Deadline" },
        { jp: "担当", romaji: "Tantou", en: "Person in charge" },
        { jp: "部長", romaji: "Buchou", en: "Department manager" },
        { jp: "課長", romaji: "Kachou", en: "Section manager" },
        { jp: "現場", romaji: "Genba", en: "Shop floor / On-site" },
        { jp: "工場", romaji: "Koujou", en: "Factory" },
        { jp: "生産", romaji: "Seisan", en: "Production" },
        { jp: "製造", romaji: "Seizou", en: "Manufacturing" },
        { jp: "納期", romaji: "Nouki", en: "Delivery date" },
        { jp: "在庫", romaji: "Zaiko", en: "Inventory / Stock" },
    ],
    qc: [
        { jp: "品質管理", romaji: "Hinshitsu kanri", en: "Quality control (QC)" },
        { jp: "品質保証", romaji: "Hinshitsu hoshou", en: "Quality assurance (QA)" },
        { jp: "検査", romaji: "Kensa", en: "Inspection" },
        { jp: "不良", romaji: "Furyou", en: "Defect / Defective" },
        { jp: "不良品", romaji: "Furyouhin", en: "Defective product" },
        { jp: "改善", romaji: "Kaizen", en: "Continuous improvement" },
        { jp: "対策", romaji: "Taisaku", en: "Countermeasure" },
        { jp: "問題", romaji: "Mondai", en: "Problem" },
        { jp: "原因", romaji: "Genin", en: "Cause / Root cause" },
        { jp: "データ", romaji: "Deeta", en: "Data" },
        { jp: "測定", romaji: "Sokutei", en: "Measurement" },
        { jp: "基準", romaji: "Kijun", en: "Standard / Criteria" },
        { jp: "規格", romaji: "Kikaku", en: "Specification" },
        { jp: "自動化", romaji: "Jidouka", en: "Automation (with human touch)" },
        { jp: "異常", romaji: "Ijou", en: "Abnormality / Anomaly" },
        { jp: "合格", romaji: "Goukaku", en: "Pass (inspection)" },
        { jp: "不合格", romaji: "Fugoukaku", en: "Fail (inspection)" },
        { jp: "ベアリング", romaji: "Bearingu", en: "Bearing" },
        { jp: "精度", romaji: "Seido", en: "Precision / Accuracy" },
    ],
    interview: [
        { jp: "はじめまして。私はレイザです。品質管理のデジタル化に興味があります。よろしくお願いします。",
          romaji: "Hajimemashite. Watashi wa Reyza desu. Hinshitsu kanri no dijitaru-ka ni kyoumi ga arimasu. Yoroshiku onegaishimasu.",
          en: "Nice to meet you. I am Reyza. I am interested in QC digitalization. Please take care of me." },
        { jp: "経験は4年以上あります", romaji: "Keiken wa yonen ijou arimasu", en: "I have more than 4 years of experience" },
        { jp: "プログラミングができます", romaji: "Puroguraming ga dekimasu", en: "I can do programming" },
        { jp: "データベースの管理ができます", romaji: "Deetabeesu no kanri ga dekimasu", en: "I can manage databases" },
        { jp: "チームワークを大切にしています", romaji: "Chiimuwaku wo taisetsu ni shiteimasu", en: "I value teamwork" },
        { jp: "品質改善に貢献したいです", romaji: "Hinshitsu kaizen ni kouken shitai desu", en: "I want to contribute to quality improvement" },
        { jp: "IoTシステムの経験があります", romaji: "IoT shisutemu no keiken ga arimasu", en: "I have experience with IoT systems" },
        { jp: "御社で成長したいです", romaji: "Onsha de seichou shitai desu", en: "I want to grow at your company" },
        { jp: "一生懸命頑張ります", romaji: "Isshoukenmei ganbarimasu", en: "I will work very hard" },
    ]
};
